### PR TITLE
Resolve several issues

### PR DESCRIPTION
**Pull request by AbhinavMadahar**
This resolves issue #8 by giving the two players a button that lets them restart a game after a GAME OVER. It differs in 2 ways from the implementation planned in #8:

1. #8 wants only a single player to have the new game button, but this PR gives both players the button. This seems more reasonable to me.
2. #8 wants the restart game button to also reset the board, but this PR keeps the same board on a game reset. This just seems cleaner to me. If you want to implement board re-selection on a game restart, then I can try to implement it.

I added a video demo of the game restart. You can watch it [here](https://youtu.be/PIeiHMKUTGw).

### CODE REVIEW

**Comment by AbhinavMadahar** [comment]
There is one thing that might be wrong. In `reactApp/src/socketlocal.js`, I changed the URL from pointing to `gameApi` to `localhost`. On my machine, this was important because `gameApi` doesn't point to anything for me. However, your deployed version might point `gameApi` to the correct place while `localhost` might not point to the right place. I'm not really sure how you deploy it. If you can shed some insight on this, then I'd appreciate it.

**Comment by AbhinavMadahar** [comment]
I added a new commit that resolves #9.

**Comment by AbhinavMadahar** [comment]
This also starts working on #30.

**Comment by 2Shaun** [comment]
> There is one thing that might be wrong. In `reactApp/src/socketlocal.js`, I changed the URL from pointing to `gameApi` to `localhost`. On my machine, this was important because `gameApi` doesn't point to anything for me. However, your deployed version might point `gameApi` to the correct place while `localhost` might not point to the right place. I'm not really sure how you deploy it. If you can shed some insight on this, then I'd appreciate it.

Really appreciate this pull request, thanks for the work you've put in. I know that this URL comes from the `services.gameApi` in `docker-compose.yml`. I have some notes in the comments there. My understanding is that containers can reference each other by name in a Docker network.

**Pull request merged**
